#!/usr/bin/perl -w
#
# This is the module's SYNOPSIS section.
#
  use Lingua::TokenParse;

  my $word = 'partition';
  my %lexicon;
  @lexicon{qw(art ion ti)} = qw(foo bar baz);
  my $obj = Lingua::TokenParse->new(
      word    => $word,
      lexicon => \%lexicon,
  );
  print scalar $obj->output_knowns;

  # Okay.  Now, let's parse a new word.
  $obj->word('metaphysical');
  $obj->lexicon({
      'meta-' => 'more comprehensive',
      'ta'    => 'foo',
      'phys'  => 'natural science, singular',
      '-ic'   => 'being, containing',
      '-al'   => 'relating to, characterized by',
  });
  $obj->rules([ qr/^me\./ ]);  # Yank combos that start with "me."
  $obj->parse;
  my @knowns = $obj->output_knowns;
